name: fibermat

channels:
    - https://conda.anaconda.org/intel
    - https://conda.anaconda.org/conda-forge
    - conda-forge
    - defaults

dependencies:
    - python>=3.8
    - pip
    - pip:
          - fibermat
          - sphinx
          - sphinx-copybutton
          - myst-parser
          - sphinx-rtd-theme
