name: fibermat

channels:
    - https://conda.anaconda.org/intel
    - https://conda.anaconda.org/conda-forge
    - conda-forge
    - defaults

dependencies:
    - python>=3.8
    - pip
    - pip:
          - fibermat
          - -r ./docs/requirements.txt
